  name: Build My App
  
  on: [push]

  jobs:
    build:
      name: Build App
      runs-on: ubuntu-latest
      steps:
        - name: Pull code
          uses: action/checkout@v2
        - name: Print dir
          run: pwd
        - name: List files
          run: ls